// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDoYeBtI-SJqTEn0LabPFBX_4UXm1tL8A',
    appId: '1:992675182588:web:b1f9d1c46d0dfcb71da479',
    messagingSenderId: '992675182588',
    projectId: 'fireapp-5e5f2',
    authDomain: 'fireapp-5e5f2.firebaseapp.com',
    storageBucket: 'fireapp-5e5f2.appspot.com',
    measurementId: 'G-KL0798P3QL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEadv-4TfxbxdvmWoqbxWj0yuTbXNRUWU',
    appId: '1:992675182588:android:a93f6988d01a571c1da479',
    messagingSenderId: '992675182588',
    projectId: 'fireapp-5e5f2',
    storageBucket: 'fireapp-5e5f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7909dTzUof2gecgcmksg7dGcpT4y82vo',
    appId: '1:992675182588:ios:ecf6d87b784202e71da479',
    messagingSenderId: '992675182588',
    projectId: 'fireapp-5e5f2',
    storageBucket: 'fireapp-5e5f2.appspot.com',
    iosClientId: '992675182588-kclm3fjaaaf38p11v82dbmmt0uib25a7.apps.googleusercontent.com',
    iosBundleId: 'shop.mtcoding.riverpodFirestoreStream',
  );
}
